import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Condensed, Roboto } from "next/font/google";
import Nav from "@/components/Nav";
import { IsFoodProvider } from "@/components/context/IsFoodContext";
import { TabsProvider } from "@/components/context/TabsContext";
import { PageProvider } from "@/components/context/PageContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <IsFoodProvider>
          <PageProvider>
            <TabsProvider>
              <Nav />
              {children}
              <Footer />
            </TabsProvider>
          </PageProvider>
        </IsFoodProvider>
      </body>
    </html>
  );
}
